---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-deployment-concourse-tasks

inputs:
- name: cf-deployment-concourse-tasks
- name: semantic_version

outputs:
- name: major_version

run:
  path: cf-deployment-concourse-tasks/ci/tasks/generate-major-version-file/task
